### ISSUE TITLE
1.8.3 tarball is missing custom_fixers

### ISSUE THREAD

**Issue by atsampson** [RDFLib/sparqlwrapper#129]
`SPARQLWrapper-1.8.3.tar.gz` is uninstallable because it doesn't include the custom_fixers directory:

```
Fixing build/lib/SPARQLWrapper/SPARQLExceptions.py build/lib/SPARQLWrapper/SmartWrapper.py build/lib/SPARQLWrapper/KeyCaseInsensitiveDict.py build/lib/SPARQLWrapper/__init__.py build/lib/SPARQLWrapper/Wrapper.py
Traceback (most recent call last):
  File "setup.py", line 84, in <module>
    'Tracker': 'https://github.com/RDFLib/sparqlwrapper/issues',
[...]
  File "/gar/lib/python3.7/lib2to3/refactor.py", line 32, in get_all_fix_names
    pkg = __import__(fixer_pkg, [], [], ["*"])
ModuleNotFoundError: No module named 'custom_fixers'
```

The Travis CI test failues since e7da403c56a94e518ccf860c6157ba33f00b073d are also the result of this.

**Comment by dayures** [comment]
@atsampson thanks for the heads up!

**Comment by atsampson** [comment]
Cheers for the quick fix :-)
