### ISSUE TITLE
Better debug support for JSON deding errors

### ISSUE THREAD

**Issue by WolfgangFahl** [RDFLib/sparqlwrapper#171]
since i couldn't make anything of the Exception 
```
Expecting property name enclosed in double quotes: line 406865 column 8 (char 11883759)
```
I got when running a SPARQL query against a Wikidata endpoint i modified the _convertJSON function to allow
to inspect the Json String that is the culprit:

```
def _convertJSON(self):
        """
        Convert a JSON result into a Python dict. This method can be overwritten in a subclass
        for a different conversion method.

        :return: converted result.
        :rtype: dict
        """
        jsonStr=self.response.read().decode("utf-8")
        try:
            return json.loads(jsonStr)
        except json.decoder.JSONDecodeError as jde:
            jsonFileName="/tmp/sparqlerror.json"
            with open(jsonFileName,"w") as jsonFile:
                        jsonFile.write(jsonStr)
            raise jde
```

the inspection of the /tmp/sparqlerror.json file revealed:
```
tail -70 sparqlerror.json
  }
  
  # region this city belongs to
  OPTIONAL {
    ?cityQ wdt:P131 ?regionId .     
  }
  
  OPTIONAL {
     ?cityQ wdt:P1082 ?cityPopulation
  }

  # country this city belongs to
  OPTIONAL {
      ?cityQ wdt:P17 ?countryId .
  }
}
java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:292)
	at com.bigdata.rdf.sail.webapp.QueryServlet.doSparqlQuery(QueryServlet.java:678)
```

I think the library should have a built-in option to analyze the json result further. The hint
**This method can be overwritten in a subclass for a different conversion method.**
already gives a hint that a specialized version of the standard approach migh be possible. How would the overriding be achieved?

I am willing to create a pullrequest based on the results of the discussion of this issue.

**Comment by WolfgangFahl** [comment]
The same issue arises if an endpoint is not properly set e.g. if you try to use https://query.wikidata.org/ as an endpoint which will return HTML code and not JSON.
