### ISSUE TITLE
Test failures probably due to remote service issues

### ISSUE THREAD

**Issue by felixonmars** [RDFLib/sparqlwrapper#222]
Hi, I am getting a lot of test failures when packaging for Arch. It seems this repo didn't get an update since March so I could not verify if it's a problem on my end or probably also a failure upstream now.

Please let me know if I can help in any way.

```
======================================================================
ERROR: testQueryToVirtuosoV8 (test.test_cli.SPARQLWrapperCLI_Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_cli.py", line 486, in testQueryToVirtuosoV8
    main(["-e", "http://dbpedia-live.openlinksw.com/sparql", "-Q", testquery])
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/SPARQLWrapper/main.py", line 137, in main
    results = sparql.query().convert()
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/SPARQLWrapper/Wrapper.py", line 960, in query
    return QueryResult(self._query())
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/SPARQLWrapper/Wrapper.py", line 940, in _query
    raise e
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/SPARQLWrapper/Wrapper.py", line 926, in _query
    response = urlopener(request)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

======================================================================
ERROR: testAskByGETinCSV (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 529, in testAskByGETinCSV
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testAskByGETinCSV_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 536, in testAskByGETinCSV_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testAskByGETinJSON (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 589, in testAskByGETinJSON
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testAskByGETinJSON_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 596, in testAskByGETinJSON_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testAskByGETinTSV (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 559, in testAskByGETinTSV
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testAskByGETinTSV_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 566, in testAskByGETinTSV_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testAskByGETinUnknow (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 732, in testAskByGETinUnknow
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testAskByGETinUnknow_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 741, in testAskByGETinUnknow_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testAskByGETinXML (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 495, in testAskByGETinXML
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testAskByGETinXML_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 503, in testAskByGETinXML_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testConstructByGETinCSV_Unexpected_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 955, in testConstructByGETinCSV_Unexpected_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testConstructByGETinJSONLD (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 900, in testConstructByGETinJSONLD
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testConstructByGETinJSONLD_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 909, in testConstructByGETinJSONLD_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testConstructByGETinN3 (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 870, in testConstructByGETinN3
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testConstructByGETinN3_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 877, in testConstructByGETinN3_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testConstructByGETinRDFXML (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 806, in testConstructByGETinRDFXML
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testConstructByGETinRDFXML_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 813, in testConstructByGETinRDFXML_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testConstructByGETinTURTLE (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 837, in testConstructByGETinTURTLE
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testConstructByGETinTURTLE_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 845, in testConstructByGETinTURTLE_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testConstructByGETinUnknow (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1054, in testConstructByGETinUnknow
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testConstructByGETinUnknow_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1062, in testConstructByGETinUnknow_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testConstructByGETinXML (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 776, in testConstructByGETinXML
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testConstructByGETinXML_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 783, in testConstructByGETinXML_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testDescribeByGETinCSV_Unexpected_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1273, in testDescribeByGETinCSV_Unexpected_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testDescribeByGETinJSONLD (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1218, in testDescribeByGETinJSONLD
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testDescribeByGETinJSONLD_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1227, in testDescribeByGETinJSONLD_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testDescribeByGETinN3 (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1188, in testDescribeByGETinN3
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testDescribeByGETinN3_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1195, in testDescribeByGETinN3_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testDescribeByGETinRDFXML (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1124, in testDescribeByGETinRDFXML
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testDescribeByGETinRDFXML_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1131, in testDescribeByGETinRDFXML_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testDescribeByGETinTURTLE (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1155, in testDescribeByGETinTURTLE
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testDescribeByGETinTURTLE_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1163, in testDescribeByGETinTURTLE_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testDescribeByGETinUnknow (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1371, in testDescribeByGETinUnknow
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testDescribeByGETinUnknow_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1379, in testDescribeByGETinUnknow_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testDescribeByGETinXML (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1094, in testDescribeByGETinXML
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testDescribeByGETinXML_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1101, in testDescribeByGETinXML_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testKeepAlive (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1422, in testKeepAlive
    sparql.query()
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/SPARQLWrapper/Wrapper.py", line 960, in query
    return QueryResult(self._query())
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/SPARQLWrapper/Wrapper.py", line 940, in _query
    raise e
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/SPARQLWrapper/Wrapper.py", line 926, in _query
    response = urlopener(request)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

======================================================================
ERROR: testSelectByGETinCSV (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 249, in testSelectByGETinCSV
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testSelectByGETinCSV_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 256, in testSelectByGETinCSV_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testSelectByGETinJSON (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 309, in testSelectByGETinJSON
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testSelectByGETinJSONLD_Unexpected (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 407, in testSelectByGETinJSONLD_Unexpected
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testSelectByGETinJSONLD_Unexpected_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 418, in testSelectByGETinJSONLD_Unexpected_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testSelectByGETinJSON_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 316, in testSelectByGETinJSON_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testSelectByGETinTSV (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 279, in testSelectByGETinTSV
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testSelectByGETinTSV_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 286, in testSelectByGETinTSV_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testSelectByGETinUnknow (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 451, in testSelectByGETinUnknow
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testSelectByGETinUnknow_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 460, in testSelectByGETinUnknow_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testSelectByGETinXML (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 215, in testSelectByGETinXML
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
ERROR: testSelectByGETinXML_Conneg (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 223, in testSelectByGETinXML_Conneg
    ct = result.info()["content-type"]
AttributeError: 'bool' object has no attribute 'info'

======================================================================
FAIL: testQueryToAllegroGraph (test.test_cli.SPARQLWrapperCLI_Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_cli.py", line 379, in testQueryToAllegroGraph
    self.assertEqual(
AssertionError: '{\n [233 chars]ont/~wildan/Kuis_Holland/D-III_Manajemen_Pemas[58 chars]n}\n' != '{\n [233 chars]ont/~mjuckes/cmip_variables_alpha/rsdcs4co2"\n[51 chars]n}\n'
  {
      "head": {
          "vars": [
              "x"
          ]
      },
      "results": {
          "bindings": [
              {
                  "x": {
                      "type": "uri",
-                     "value": "https://mmisw.org/ont/~wildan/Kuis_Holland/D-III_Manajemen_Pemasaran"
+                     "value": "https://mmisw.org/ont/~mjuckes/cmip_variables_alpha/rsdcs4co2"
                  }
              }
          ]
      }
  }


======================================================================
FAIL: testQueryToBrazeGraph (test.test_cli.SPARQLWrapperCLI_Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_cli.py", line 547, in testQueryToBrazeGraph
    self.assertEqual(
AssertionError: '{\n [218 chars]p://www.wikidata.org/entity/statement/Q125-CBA[87 chars]n}\n' != '{\n [218 chars]p://wikiba.se/ontology#Dump"\n                [35 chars]n}\n'
  {
      "head": {
          "vars": [
              "x"
          ]
      },
      "results": {
          "bindings": [
              {
                  "x": {
                      "type": "uri",
-                     "value": "http://www.wikidata.org/entity/statement/Q125-CBA36E99-7E0C-4A0A-90D6-7F819E773C70"
+                     "value": "http://wikiba.se/ontology#Dump"
                  }
              }
          ]
      }
  }


======================================================================
FAIL: testQueryBadFormed (test.test_virtuoso__v8_03_3313__dbpedia.SPARQLWrapperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_virtuoso__v8_03_3313__dbpedia.py", line 1407, in testQueryBadFormed
    self.assertRaises(QueryBadFormed, self.__generic, queryBadFormed, XML, GET)
AssertionError: QueryBadFormed not raised by __generic

======================================================================
FAIL: testConvert (test.test_wrapper.QueryResult_Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_wrapper.py", line 886, in testConvert
    self.assertEqual(1, _mime_vs_type("application/x-foo-bar", XML), "invalid mime")
AssertionError: 1 != 0 : invalid mime

======================================================================
FAIL: testPrint_results (test.test_wrapper.QueryResult_Test)
print_results() is only allowed for JSON return format.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_wrapper.py", line 938, in testPrint_results
    self.assertEqual(1, _print_results("application/sparql-results+xml"))
AssertionError: 1 != 0

======================================================================
FAIL: testSetReturnFormat (test.test_wrapper.SPARQLWrapper_Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sparqlwrapper/src/sparqlwrapper-2.0.0/test/test_wrapper.py", line 198, in testSetReturnFormat
    self.assertEqual(1, len(w), "Warning due to non expected format")
AssertionError: 1 != 0 : Warning due to non expected format

----------------------------------------------------------------------
Ran 1335 tests in 918.979s

FAILED (failures=6, errors=50, skipped=476, expected failures=64)
http://vocabs.ands.org.au/repository/api/sparql/csiro_international-chronostratigraphic-chart_2018-revised-corrected?query=%0APREFIX+rdfs%3A+%3Chttp%3A//www.w3.org/2000/01/rdf-schema%23%3E%0APREFIX+skos%3A+%3Chttp%3A//www.w3.org/2004/02/skos/core%23%3E%0A%0A++++DESCRIBE+%3Chttp%3A//resource.geosciml.org/classifier/ics/ischart/Jurassic%3E%0A
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
HTTP Error 502: Bad Gateway
``

**Comment by dayures** [comment]
Thanks for the heads up. Probably there was an issue with external SPARQL endpoints. Some of the tests have been updates in #251 

I am going to close the issue. Please re-open it if the issue reappears.
