### ISSUE TITLE
QueryBadFormed: A bad request has been sent to the endpoint

### ISSUE THREAD

**Issue by rjalexa** [RDFLib/sparqlwrapper#224]
I am not understanding the source of this error. Here is a fully functional test code:
```
from SPARQLWrapper import SPARQLWrapper, JSON
endpoint = "http://dati.senato.it/sparql"
sparql = SPARQLWrapper(endpoint)
sparql.setReturnFormat(JSON)
# just a simple query only to debug
sparqlquery = "SELECT * WHERE {?s ?p ?o} LIMIT 1"
sparql.setQuery(sparqlquery)
ret = sparql.queryAndConvert()
```
which generates the following error message:
```
Exception has occurred: QueryBadFormed
QueryBadFormed: A bad request has been sent to the endpoint: probably the SPARQL query is badly formed. 

Response:
b"Virtuoso 37000 Error SP030: SPARQL compiler, line 0: Invalid character in SPARQL expression at '%'\n\nSPARQL query:\ndefine sql:big-data-const 0 \n#output-format:application/sparql-results+json\nSELECT %2A WHERE %7B%3Fs %3Fp %3Fo%7D LIMIT 1"
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

  File "/Users/bob/Documents/work/getnews/python test/misc/senato.py", line 18, in <module>
    ret = sparql.queryAndConvert()
          ^^^^^^^^^^^^^^^^^^^^^^^^
SPARQLWrapper.SPARQLExceptions.QueryBadFormed: QueryBadFormed: A bad request has been sent to the endpoint: probably the SPARQL query is badly formed. 

Response:
b"Virtuoso 37000 Error SP030: SPARQL compiler, line 0: Invalid character in SPARQL expression at '%'\n\nSPARQL query:\ndefine sql:big-data-const 0 \n#output-format:application/sparql-results+json\nSELECT %2A WHERE %7B%3Fs %3Fp %3Fo%7D LIMIT 1"

```
**Environment:**
```
MacOS Ventura
python                    3.11.0          h559f36b_0_cpython    conda-forge
sparqlwrapper             2.0.0              pyha770c72_0    conda-forge
```

**Comment by fabmeyer** [comment]
I am having a similiar issue for a query that works elsewhere.
```
Traceback (most recent call last):
  File "/home/fabmeyer/.local/share/virtualenvs/analytics-nko8goOs/lib/python3.9/site-packages/SPARQLWrapper/Wrapper.py", line 926, in _query
    response = urlopener(request)
  File "/home/fabmeyer/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/fabmeyer/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/fabmeyer/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/fabmeyer/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/fabmeyer/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/fabmeyer/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fabmeyer/Dev/Python/analytics/GraphDB.py", line 29, in <module>
    results = sparql.query().convert()
  File "/home/fabmeyer/.local/share/virtualenvs/analytics-nko8goOs/lib/python3.9/site-packages/SPARQLWrapper/Wrapper.py", line 960, in query
    return QueryResult(self._query())
  File "/home/fabmeyer/.local/share/virtualenvs/analytics-nko8goOs/lib/python3.9/site-packages/SPARQLWrapper/Wrapper.py", line 930, in _query
    raise QueryBadFormed(e.read())
SPARQLWrapper.SPARQLExceptions.QueryBadFormed: QueryBadFormed: A bad request has been sent to the endpoint: probably the SPARQL query is badly formed. 

Response:
b'MALFORMED QUERY: Encountered " "{" "{ "" at line 5, column 12.\r\nWas expecting one of:\r\n    "(" ...\r\n    "*" ...\r\n    "distinct" ...\r\n    "reduced" ...\r\n    <VAR1> ...\r\n    <VAR2> ...\r\n    '
```

**Comment by dayures** [comment]
Thanks for the detailed report. This is not actually a malformed SPARQL query, `SELECT * WHERE {?s ?p ?o} LIMIT 1` is valid

Just tested on my laptop and it is working. I’m closing this ticket. If someone can still reproduce with current SPARQLWrapper using the settings above, feel free to open a new issue with a minimal repro.
