### ISSUE TITLE
 GraphDB 10.2.2: b'Missing parameter: query' on INSERT

### ISSUE THREAD

**Issue by frantony** [RDFLib/sparqlwrapper#233]
I use SPARQLWrapper version 1.8.5-152-g2a6e2d3 with GraphDB 10.2.2 SPARQL endpoint.

Here is my ``my-example-insert.py`` script:

```
from SPARQLWrapper import SPARQLWrapper, POST

sparql = SPARQLWrapper("http://172.17.0.3:7200/repositories/test")

sparql.setMethod(POST)

sparql.setQuery("""
WITH <http://example.graph>
INSERT
{ <http://dbpedia.org/resource/Asturias> rdfs:label "Asturies"@ast }
""")

results = sparql.query()
print(results.response.read())
```

The script output:

```
$ python3 my-example-insert.py
Traceback (most recent call last):
  File "/workdir/test-sparql/SPARQLWrapper/Wrapper.py", line 926, in _query
    response = urlopener(request)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workdir/test-sparql/example-delete.py", line 13, in <module>
    results = sparql.query()
              ^^^^^^^^^^^^^^
  File "/workdir/test-sparql/SPARQLWrapper/Wrapper.py", line 960, in query
    return QueryResult(self._query())
                       ^^^^^^^^^^^^^
  File "/workdir/test-sparql/SPARQLWrapper/Wrapper.py", line 930, in _query
    raise QueryBadFormed(e.read())
SPARQLWrapper.SPARQLExceptions.QueryBadFormed: QueryBadFormed: A bad request has been sent to the endpoint: probably the SPARQL query is badly formed. 

Response:
b'Missing parameter: query'
```

I have the same problem with the ``DELETE`` request.

**Comment by rajaram5** [comment]
I ran into same issue. Did you manage to find a solution? @frantony

**Comment by frantony** [comment]
@rajaram5 

> Did you manage to find a solution? 

My solution is

* use ClioPatria server instead of GraphDB;
* apply this patch to sparqlwrapper:
```
diff --git a/SPARQLWrapper/Wrapper.py b/SPARQLWrapper/Wrapper.py
index 977380a..b93c0e2 100644
--- a/SPARQLWrapper/Wrapper.py
+++ b/SPARQLWrapper/Wrapper.py
@@ -844,7 +844,7 @@ class SPARQLWrapper(object):
                 request = urllib.request.Request(uri)
                 request.add_header("Content-Type", "application/x-www-form-urlencoded")
                 request.data = self._getRequestEncodedParameters(
-                    ("update", self.queryString)
+                    ("query", self.queryString)
                 ).encode("ascii")
         else:
             # protocol details at http://www.w3.org/TR/sparql11-protocol/#query-operation

```

**Comment by ashleysommer** [comment]
I know this is old, but I'll respond here with what the issue is.
GraphDB has two different SPARQL endpoints. One for queries, one for updates.
The one you're using (`http://172.17.0.3:7200/repositories/test`) is the query endpoint. It only supports read-only query reuests, no updates, inserts or deletes.
The GraphDB update endpoint looks like: `http://172.17.0.3:7200/repositories/test/statements` 

You need to construct your sparqlwrapper instance like this:
```
sparql = SPARQLWrapper(
    "http://172.17.0.3:7200/repositories/test",
    updateEndpoint = "http://172.17.0.3:7200/repositories/test/statements",
)
sparql.setMethod(POST)
```

**Comment by frantony** [comment]
@ashleysommer 

Thanks a lot!

According to https://cliopatria.swi-prolog.org/help/http ClioPatria uses the ``/sparql/update`` endpoint for update requests, e.g.

```
sparqlwrapper_endpoint="http://127.0.0.1:3020/sparql"

sparql = SPARQLWrapper.SPARQLWrapper(sparqlwrapper_endpoint,
                                     updateEndpoint=sparqlwrapper_endpoint + "/update")

```
